/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCliente;
import Controlador.ControladorProducto;
import java.awt.Dimension;
import javax.swing.JInternalFrame;
import Controlador.ControladorUsuario;
import Modulo.Cliente;

/**
 *
 * @author mardc
 */
public class MenuSR extends javax.swing.JFrame {

    /**
     * Creates new form MenuSR
     */
    public MenuSR() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaSR = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        SubMenuVenta = new javax.swing.JMenu();
        SR_SubMenuVenta = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        SR_SubMenuProducto = new javax.swing.JMenuItem();
        SR_SubMenuUsuario = new javax.swing.JMenuItem();
        SR_SubMenuCliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VentanaSR.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout VentanaSRLayout = new javax.swing.GroupLayout(VentanaSR);
        VentanaSR.setLayout(VentanaSRLayout);
        VentanaSRLayout.setHorizontalGroup(
            VentanaSRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        VentanaSRLayout.setVerticalGroup(
            VentanaSRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 255, Short.MAX_VALUE)
        );

        jMenu1.setText("Menu");

        jMenuItem1.setText("ayuda");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Salir");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        SubMenuVenta.setText("Venta");

        SR_SubMenuVenta.setText("Generar Venta");
        SubMenuVenta.add(SR_SubMenuVenta);

        jMenuBar1.add(SubMenuVenta);

        jMenu3.setText("Mantenimiento");

        SR_SubMenuProducto.setText("Producto");
        SR_SubMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SR_SubMenuProductoActionPerformed(evt);
            }
        });
        jMenu3.add(SR_SubMenuProducto);

        SR_SubMenuUsuario.setText("usuario");
        SR_SubMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SR_SubMenuUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(SR_SubMenuUsuario);

        SR_SubMenuCliente.setText("Cliente");
        SR_SubMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SR_SubMenuClienteActionPerformed(evt);
            }
        });
        jMenu3.add(SR_SubMenuCliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentanaSR)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VentanaSR)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SR_SubMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SR_SubMenuUsuarioActionPerformed
        UsuarioForm user = new UsuarioForm();
        ControladorUsuario cu = new ControladorUsuario(user);
        CentrarVentana(user);
    }//GEN-LAST:event_SR_SubMenuUsuarioActionPerformed

    private void SR_SubMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SR_SubMenuClienteActionPerformed
        ClienteForm cf = new ClienteForm();
        ControladorCliente cc = new ControladorCliente(cf);
        CentrarVentana(cf);
    }//GEN-LAST:event_SR_SubMenuClienteActionPerformed

    private void SR_SubMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SR_SubMenuProductoActionPerformed
        ProductoForm registro = new ProductoForm();
        ControladorProducto cp = new ControladorProducto(registro);
        CentrarVentana(registro);
    }//GEN-LAST:event_SR_SubMenuProductoActionPerformed
    //FUNCION PARA CENTRAR EL MENU SR
    //LLAMAR EN LA ULTIMA LINEA
    void CentrarVentana(JInternalFrame frame){
        VentanaSR.add(frame);
        Dimension dimension = VentanaSR.getSize();
        Dimension Dframe = frame.getSize();
        
        frame.setLocation((dimension.width - Dframe.height)/2,(dimension.height - Dframe.width)/2);
        frame.show();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MenuSR().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SR_SubMenuCliente;
    private javax.swing.JMenuItem SR_SubMenuProducto;
    private javax.swing.JMenuItem SR_SubMenuUsuario;
    private javax.swing.JMenuItem SR_SubMenuVenta;
    private javax.swing.JMenu SubMenuVenta;
    private javax.swing.JDesktopPane VentanaSR;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
